spring:
  datasource:
    url: jdbc:postgresql://url.supabase.co:5432/postgres?user=postgres&password=[password]
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG